In [87]:
import numpy as np
from pymatgen.ext.matproj import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [88]:
mp_key = "kqoGOG3L85VvUgz1hujhLArYSrmj87fq"
mp_id = "mp-10182"

In [89]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()
sites = conv_struc.sites

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# 3 éléments de symétrie

In [90]:
i = 6
print(symmops[i],"\n")

l = 2
at1 = sites[l]
op1 = symmops[i]

pos_init1 = at1.frac_coords
print("Avant symétrie:",pos_init1)

pos_final1 = op1.operate(pos_init1)
print("Après symétrie:",pos_final1)

# représentation 3D
view1 = quick_view(conv_struc)
display(view1)
view1.script('draw SYMOP ' + str(i+1) + ' {atomno = ' + str(4) + '}')

1:
Rot:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.] 

Avant symétrie: [0.75 0.75 0.75]
Après symétrie: [-0.75  0.75 -0.75]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Premier élément de symétrie
Le premier élément de symétrie fait passer des coordonnées (x,y,z) aux coordonnées (-x,y,-z). Il s'agit d'une rotation du deuxième ordre (de 180°) autour de l'axe b. 
La matrice de rotation représentant cette opération est :

\begin{pmatrix}
-1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & -1
\end{pmatrix}

Le vecteur représentant la translation est nul: $\begin{pmatrix}
0 & 0 & 0
\end{pmatrix}$

Cet élément est appliqué à l'atome Li dont les coordonnées réduites sont : $\begin{pmatrix}
0.75 & 0.75 & 0.75
\end{pmatrix} \rightarrow \begin{pmatrix}
-0.75 & 0.75 & -0.75
\end{pmatrix}$

In [91]:
j = 5
print(symmops[j],"\n")


m = 4
at2 = sites[m]
op2 = symmops[j]

pos_init2 = at2.frac_coords
print("Avant symétrie:",pos_init2)
 
pos_final2 = op2.operate(pos_init2)
print("Après symétrie:",pos_final2)

# représentation 3D
view2 = quick_view(conv_struc)
display(view2)
view2.script('draw SYMOP ' + str(j + 1) + ' {atomno = ' + str(m + 1) + '}')

2:
Rot:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.] 

Avant symétrie: [0.75 0.25 0.75]
Après symétrie: [0.25 0.75 0.75]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Deuxième élément de symétrie
Le deuxième élément de symétrie fait passer des coordonnées (x,y,z) aux coordonnées (y,x,z). Il s'agit d'un plan miroir m, le plan $\begin{pmatrix}
1 & \bar{1} & 0
\end{pmatrix}
$. 
La matrice de rotation représentant cette opération est :

\begin{pmatrix}
0 & 1 & 0\\
1 & 0 & 0\\
0 & 0 & 1
\end{pmatrix}

Le vecteur représentant la translation est nul: $\begin{pmatrix}
0 & 0 & 0
\end{pmatrix}$

Cet élément est appliqué à l'atome Zn dont les coordonnées réduites sont : $\begin{pmatrix}
0.75 & 0.25 & 0.75
\end{pmatrix} \rightarrow \begin{pmatrix}
0.25 & 0.75 & 0.75
\end{pmatrix}$

In [92]:
k = 24
print(symmops[k],"\n")

n = 8
at3 = sites[n]
op3 = symmops[k]

pos_init3 = at3.frac_coords
print("Avant symétrie:",pos_init3)

pos_final3 = op3.operate(pos_init3)
print("Après symétrie:",pos_final3)

# représentation 3D
view3 = quick_view(conv_struc)
display(view3)
view3.script('draw SYMOP ' + str(k + 1) + ' {atomno = ' + str(n + 1) + '}')

3:
Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0.5 0.5 0. ] 

Avant symétrie: [0. 0. 0.]
Après symétrie: [0.5 0.5 0. ]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Troisième élément de symétrie
Le troisième élément de symétrie fait passer des coordonnées (x,y,z) aux coordonnées (x+1/2,y+1/2,z). Il s'agit d'une translation pure.
La matrice de rotation représentant cette opération est donc la matrice identité:

\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}

Le vecteur représentant la translation est $\begin{pmatrix}
0.5 & 0.5 & 0
\end{pmatrix}$.

Cet élément est appliqué à l'atome P dont les coordonnées réduites sont : $\begin{pmatrix}
0 & 0 & 0
\end{pmatrix} \rightarrow \begin{pmatrix}
0.5 & 0.5 & 0
\end{pmatrix}$